server:
  port: 8080  # මෙය service එක run වෙන්නේ කුමන port එකෙද කියලා සඳහන් කරනවා (Set the port where the API Gateway will run)

spring:
  application:
    name: api-gateway  # මේක application එකට දෙන නමයි (This is the name of the application, used for service registration)

  cloud:
    loadbalancer:
      ribbon:
        enabled: false  # Ribbon load balancer එක අක්‍රීය කරනවා (Disables the default Ribbon load balancer)


    gateway:
      routes:
        - id: products-service
          uri: http://localhost:8081
          predicates:
           - Path=/products-service/**


        - id: order-service
          uri: http://localhost:8082
          predicates:
            - Path=/order-service/**


        - id: inventory-service
          uri: http://localhost:3000
          predicates:
            - Path=/inventory-service/**


        - id: customer-service
          uri: http://localhost:5000
          predicates:
            - Path=/customer-service/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Eureka Server එකේ ලිපිනය මෙන්න (This is the URL of the Eureka Server for service discovery)
