server:
  port: 8081
  servlet:
    context-path: /products-service



spring:
  application:
    name: products-service


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/